name       : lyrebird
version    : 1.1.0
release    : 1
source     :
    - https://github.com/lyrebird-voice-changer/lyrebird/archive/refs/tags/v1.1.0.tar.gz : 5a9de231bf2f75c83af29349bc1c52d366c489be0b69c3cb0ddcbfffcf75de34
license    : MIT
component  : multimedia.audio
summary    : Simple and powerful voice changer for Linux
description: |
    Simple and powerful voice changer for Linux
rundeps    :
    - pavucontrol
    - python-gobject
    - python-toml
    - sox
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_and_requirements.patch
install    : |
    export INSTALL_PREFIX=$installdir/usr
    ./install.sh
